/**
 * The native QR scanner's wiring, which nothing else can check before a phone
 * has the APK on it.
 *
 * The scanner is a vendored Tauri plugin (`src-tauri/plugins/barcode-scanner`)
 * driven by four direct `invoke` calls in `web/src/desktop.ts`. Every part of
 * that chain fails at RUNTIME, on a phone, and only there:
 *
 *   - a command the capability file does not allow is refused by Tauri with
 *     "not allowed", and the scanner simply does not open;
 *   - a permission naming a command the plugin does not have is accepted by
 *     nobody and rejected at build time, which is better but still late;
 *   - a plugin that is declared and never `init()`ed answers every invoke with
 *     "plugin not found".
 *
 * None of that shows up in the web build, in the desktop build, or in a
 * browser, because on all three the whole path is dead code. So the chain is
 * checked here, from the strings the webview sends to the commands the plugin
 * declares it has.
 */

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const PLUGIN = join(root, 'src-tauri', 'plugins', 'barcode-scanner')
const read = (...p: string[]) => readFileSync(join(root, ...p), 'utf8')

/** The commands the plugin's own build script says it has. */
const declared = (): Set<string> => {
  const list = readdirSync(join(PLUGIN, 'permissions', 'autogenerated', 'commands'))
  return new Set(list.filter((f) => f.endsWith('.toml')).map((f) => f.slice(0, -'.toml'.length)))
}

/** Every `plugin:barcode-scanner|<command>` the web code sends. */
const invoked = (): string[] => {
  const src = read('web', 'src', 'desktop.ts')
  return [...src.matchAll(/plugin:barcode-scanner\|([a-z_]+)/g)].map((m) => m[1])
}

/** The `allow-<command>` entries of the phone capability. */
const allowed = (): string[] => {
  const cap = JSON.parse(read('src-tauri', 'capabilities', 'mobile.json'))
  return cap.permissions.map((p: string) => {
    const [plugin, perm] = p.split(':')
    assert.equal(plugin, 'barcode-scanner', `mobile.json grants ${p}, which is not the scanner`)
    return perm.replace(/^allow-/, '').replace(/-/g, '_')
  })
}

test('every command the webview sends exists in the plugin', () => {
  const have = declared()
  const sent = invoked()
  assert.ok(sent.length >= 4, `desktop.ts invokes ${sent.length} scanner commands, expected the four`)
  for (const c of sent) assert.ok(have.has(c), `desktop.ts invokes "${c}", which the plugin does not have`)
})

test('every command the webview sends is allowed by the capability', () => {
  const ok = new Set(allowed())
  for (const c of invoked()) {
    assert.ok(ok.has(c), `"${c}" is invoked but not allowed in capabilities/mobile.json`)
  }
})

test('the capability allows nothing the plugin does not have', () => {
  const have = declared()
  for (const c of allowed()) {
    assert.ok(have.has(c), `capabilities/mobile.json allows "${c}", which is not a command of this plugin`)
  }
})

test('the capability is phone-only', () => {
  const cap = JSON.parse(read('src-tauri', 'capabilities', 'mobile.json'))
  // A desktop that loaded this would fail to build: the plugin is `#![cfg(mobile)]`
  // and there is no `init()` to permit outside a phone.
  assert.deepEqual(cap.platforms, ['android', 'iOS'])
  assert.deepEqual(cap.windows, ['main'])
})

test('the plugin is depended on for phones only, and initialised there', () => {
  const cargo = read('src-tauri', 'Cargo.toml')
  const dep = cargo.indexOf('tauri-plugin-barcode-scanner = { path = "plugins/barcode-scanner" }')
  assert.ok(dep > 0, 'Cargo.toml does not use the vendored scanner')
  // The section it sits under is the mobile one: on a desktop target the crate
  // compiles to nothing, and `init()` would not exist to call.
  const section = cargo.lastIndexOf('[target.', dep)
  assert.match(cargo.slice(section, dep), /target_os = "android"/)

  const rs = read('src-tauri', 'src', 'lib.rs')
  const mobile = rs.indexOf('mod mobile {')
  assert.ok(mobile > 0, 'lib.rs has no mobile module')
  assert.ok(rs.indexOf('tauri_plugin_barcode_scanner::init()') > mobile,
    'the scanner plugin is never initialised inside the mobile module')
})

test('the page goes transparent while the native scanner runs', () => {
  // The camera preview is drawn BEHIND the webview. Without these rules the
  // user aims a camera at a card they cannot see through - the scanner works
  // and looks broken.
  const html = read('web', 'index.html')
  assert.match(html, /html\.scanning,html\.scanning body\{background:transparent!important\}/)
  assert.match(html, /html\.scanning #app\{visibility:hidden\}/)
  // The scanner is opened from the "add a peer" modal, which is a SIBLING of
  // #app: hiding the app leaves it standing on top of the camera picture.
  assert.match(html, /html\.scanning \.modal:not\(#scan-modal\)[^{]*\{display:none\}/)
  // The aiming window, and where it must NOT be: `position:fixed` inside a
  // transformed ancestor is positioned against that ancestor, and the scan
  // modal is translated - with the frame as its child it drew around the
  // buttons instead of the middle of the screen.
  assert.match(html, /id="scan-vf"/)
  assert.ok(html.indexOf('id="scan-vf"') < html.indexOf('id="scan-modal"'),
    'the viewfinder must be a sibling BEFORE the scan modal, not inside it')
  assert.match(html, /html\.scanning #scan-vf\{[^}]*box-shadow:0 0 0 100vmax/,
    'the dimming around the frame is the spread shadow; without it there is no frame')

  const app = read('web', 'src', 'app.ts')
  assert.ok(app.includes("classList.add('scanning')"), 'app.ts never marks the page as scanning')
  assert.ok(app.includes("classList.remove('scanning')"), 'app.ts never takes the mark off again')
})
