/**
 * origin.ts — who sent a frame, read from the frame itself.
 *
 * Every module that listens on a topic keys its state by the SENDER: the room
 * keeps EH-2 sessions and ratchets per `from`, presence and the self-topic
 * compare `from` with `self`. Today that id comes from the transport --
 * GossipSub hands over the publisher's PeerId with each message. That works
 * only while every client publishes for itself. The moment a relay publishes
 * on a client's behalf (`/onchato/push`, the light-client plan, stage 2) the
 * transport says `from = relay` for everybody, and every session collapses
 * into one.
 *
 * So the sender moves INTO the frame, the way Announce has carried `peer` in
 * its payload from the start (§5.5). One outer envelope around any frame that
 * goes on a topic:
 *
 *   [0xE1][u8 fromLen][from utf8][inner frame, unchanged]
 *
 * `origin(evt)` is what a handler calls first: a tagged frame yields the
 * sender from the envelope and the inner bytes; an untagged frame yields the
 * transport's sender and the bytes as they came. Both forms are read for as
 * long as clients that write the old one exist. Nothing else in a handler
 * changes -- it sees the same `from` and the same `data` it always did.
 *
 * ## Why 0xE1 is free
 *
 * The first byte of every frame family on a pair, self or group topic is
 * fixed and none of them is 0xE1: EH-2 handshake 0x01-0x03 (eh2/wire.ts),
 * ratchet data 0x10 (eh2/ratchet.ts), group message 0x20 and keepalive 0x21
 * (lib/group.ts, lib/grouproom.ts), Announce is JSON so 0x7B. The ONE family
 * that can start with anything is the knock on an inbox topic -- its first 32
 * bytes are a random ephemeral key (lib/knock.ts). The inbox therefore never
 * calls `origin()`: a knock does not use `from` at all, and a decoy has to stay
 * indistinguishable from a real knock, which an envelope with a readable
 * sender would break. Keep it that way.
 *
 * ## What `from` is, and is not
 *
 * A PeerId in the envelope is a CLAIM, where the transport's was signed
 * (StrictSign). That changes nothing about security, and it is worth being
 * exact about why: a libp2p id is generated by whoever shows up, so an
 * attacker could always arrive under any `from`. `from` selects state -- which
 * session, which handshake -- and the state itself is protected by EH-2 and
 * the ratchet. A forged `from` lands a frame in the wrong session, where it
 * does not open, exactly as today. `from` must never be used as proof of
 * identity, and a review of the callers found no place that does.
 *
 * The field is opaque bytes on the wire. Today it holds the libp2p PeerId
 * string because that is what the callers key on; a client that stops being a
 * libp2p peer can put a random per-session id there without touching this
 * module.
 */

export const TAG = 0xe1

const enc = new TextEncoder()
const dec = new TextDecoder()
const MAX_FROM = 255

/** Put the sender in front of a frame. `from` must fit one byte of length. */
export function wrap(from: string, frame: Uint8Array): Uint8Array {
  const f = enc.encode(from)
  if (!f.length || f.length > MAX_FROM) throw new Error(`origin: from of ${f.length} bytes does not fit`)
  const out = new Uint8Array(2 + f.length + frame.length)
  out[0] = TAG
  out[1] = f.length
  out.set(f, 2)
  out.set(frame, 2 + f.length)
  return out
}

/**
 * Take the sender off a tagged frame. `null` for a frame that is not tagged
 * (the caller then uses the transport's sender) AND for a tagged frame whose
 * length does not fit -- the two are told apart with `isTagged`.
 */
export function unwrap(bytes: Uint8Array): { from: string; frame: Uint8Array } | null {
  if (!isTagged(bytes)) return null
  const n = bytes[1]
  if (!n || 2 + n > bytes.length) return null
  return { from: dec.decode(bytes.subarray(2, 2 + n)), frame: bytes.subarray(2 + n) }
}

export function isTagged(bytes: Uint8Array): boolean {
  return bytes instanceof Uint8Array && bytes.length >= 2 && bytes[0] === TAG
}

/**
 * The first thing a topic handler does with a pubsub `message` event: the
 * sender and the frame, whichever form they arrived in. `null` means a tagged
 * frame that does not parse -- drop it, there is no sender to attribute it to.
 */
export function origin(evt: { detail: { data: Uint8Array; from?: { toString(): string } } }):
  { from: string; data: Uint8Array } | null {
  const data: Uint8Array = evt.detail.data
  if (isTagged(data)) {
    const u = unwrap(data)
    return u ? { from: u.from, data: u.frame } : null
  }
  return { from: evt.detail.from?.toString?.() ?? '', data }
}
